"""Initial schema

Revision ID: a2d83a612ff7
Revises:
Create Date: 2026-10-04 00:37:31.355307

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2d83a612ff7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price_paise", sa.BigInteger(), nullable=False),
        sa.Column("per_user_limit", sa.Integer(), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="service",
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["service.shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "show_id", "user_id", "idempotency_key", name="uix_show_user_idempotency"
        ),
        schema="service",
    )
    op.create_table(
        "seats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("seat_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["service.shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "seat_number", name="uix_show_seat"),
        schema="service",
    )
    op.create_table(
        "user_show_booking_state",
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("active_seat_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["service.shows.id"],
        ),
        sa.PrimaryKeyConstraint("show_id", "user_id"),
        schema="service",
    )
    op.create_table(
        "reservation_seats",
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("seat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["service.reservations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"],
            ["service.seats.id"],
        ),
        sa.PrimaryKeyConstraint("reservation_id", "seat_id"),
        schema="service",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservation_seats", schema="service")
    op.drop_table("user_show_booking_state", schema="service")
    op.drop_table("seats", schema="service")
    op.drop_table("reservations", schema="service")
    op.drop_table("shows", schema="service")
    # ### end Alembic commands ###
